## TASK 09 - Chipotle Case study
> + Name : Anvesh Hirve
> + Batch no : 550
> + Module : EDA - Exploratory Data Analysis

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Anvesh\OneDrive\Desktop\Innomatics Research Labs Module\EDA_550\data\data\chipotle (1).csv")

In [3]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
994,408,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.25
995,409,1,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Red Chi...",$8.49
996,409,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98
997,410,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Rice, Black Beans]]",$8.75
998,410,1,Canned Soft Drink,[Diet Coke],$1.25

#### 1. Remove the $ symbol from the item_price column and convert it to numeric data.

In [4]:
df['item_price'] = df['item_price'].str.replace('$','')
df['item_price'] = df['item_price'].astype('float')

In [5]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
994,408,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.25
995,409,1,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Red Chi...",8.49
996,409,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",10.98
997,410,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Rice, Black Beans]]",8.75
998,410,1,Canned Soft Drink,[Diet Coke],1.25

#### 2. How many products cost more than $10?

In [6]:
df[df['item_price']>10]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
...,...,...,...,...,...
990,407,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.25
991,407,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
993,408,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Sour Crea...",11.25
994,408,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.25
996,409,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",10.98

In [7]:
df[df['item_price']>10].sum()

order_id                                                          47395
quantity                                                            260
item_name             Chicken BowlChicken BowlSteak BurritoChicken B...
choice_description    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
item_price                                                      2846.07
dtype: object

#### 3. What is the maximum price of the Chicken Bowl item?

In [8]:
df[(df['item_name']=='Chicken Bowl')]['item_price'].max()

32.94

#### 4. Extract the unique item_name available for less than $5.

In [9]:
df[df['item_price']<5]['item_name'].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Side of Chips',
       'Chips and Guacamole', 'Canned Soda', 'Bottled Water',
       'Chips and Tomatillo Green Chili Salsa', 'Chips',
       'Chips and Tomatillo Red Chili Salsa',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Canned Soft Drink',
       'Chips and Tomatillo-Red Chili Salsa',
       'Chips and Mild Fresh Tomato Salsa'], dtype=object)

#### 5. Identify the order_id that has placed the most orders.

In [10]:
df['order_id'].value_counts().idxmax()

np.int64(205)

#### 6. Which is the most ordered item_name?

In [11]:
df['item_name'].value_counts().idxmax()

'Chicken Burrito'

#### 7. Find the minimum and maximum price in the item_price column.

In [12]:
print("Minimum Price: ",df['item_price'].min())
print("Maximum Price: ",df['item_price'].max())

Minimum Price:  1.09
Maximum Price:  32.94

#### 8. Find the most expensive dish (item_name).

In [13]:
df[df['item_price']==df['item_price'].max()]['item_name']

409    Chicken Bowl
Name: item_name, dtype: object

#### 9. Calculate the total amount for orders where the item_name is Canned Soft Drink and the choice_description is Lemonade.

In [22]:
df[(df['item_name']=='Canned Soft Drink') & (df['choice_description']== '[Lemonade]')]['item_price'].sum()

np.float64(12.5)

#### 10. Use loc to extract all orders where the item_price is greater than $10 and belongs to the Chicken Bowl.

In [25]:
df.loc[(df['item_price']>10) & (df['item_name']=='Chicken Bowl')]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
123,54,1,Chicken Bowl,"[Fresh Tomato Salsa, [Guacamole, Cheese, Sour ...",11.25
138,62,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.25
140,63,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Sour Crea...",11.25
142,64,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
176,79,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",10.98
199,89,1,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",10.98
209,93,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
211,93,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
282,124,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",17.50
290,126,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
291,127,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Sour Crea...",11.25
303,132,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
379,165,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
407,177,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.25
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
411,179,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",11.25
415,181,2,Chicken Bowl,[Tomatillo Red Chili Salsa],17.50
454,195,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
483,205,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
490,206,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
501,210,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
546,227,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",11.25
548,228,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",10.98
583,239,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
654,271,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
668,277,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
687,284,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
706,290,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Sour Crea...",11.25
719,297,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",11.25
765,316,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
798,328,1,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",10.98
817,338,1,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",10.98
844,347,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Guacamole]]",11.25
849,350,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
871,360,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Sour Cream,...",11.25
877,362,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
892,369,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Fajita Vegg...",10.98
915,379,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
975,400,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.25
976,401,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
993,408,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Sour Crea...",11.25
994,408,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.25
996,409,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",10.98

#### 11. Use iloc to extract the first 10 rows of the dataset and display only order_id, item_name, and item_price.

In [27]:
df.iloc[0:10,0::2]

   order_id                              item_name  item_price
0         1           Chips and Fresh Tomato Salsa        2.39
1         1                                   Izze        3.39
2         1                       Nantucket Nectar        3.39
3         1  Chips and Tomatillo-Green Chili Salsa        2.39
4         2                           Chicken Bowl       16.98
5         3                           Chicken Bowl       10.98
6         3                          Side of Chips        1.69
7         4                          Steak Burrito       11.75
8         4                       Steak Soft Tacos        9.25
9         5                          Steak Burrito        9.25

#### 12. Find the top 3 most ordered items

In [30]:
df['item_name'].value_counts().head(3)

item_name
Chicken Burrito        125
Chicken Bowl           119
Chips and Guacamole    110
Name: count, dtype: int64

#### 13. Extract all unique choice_description for items costing more than $15

In [28]:
df[df['item_price']>15]['choice_description'].unique()

array(['[Tomatillo-Red Chili Salsa (Hot), [Black Beans, Rice, Cheese, Sour Cream]]',
       '[Tomatillo Green Chili Salsa, [Sour Cream, Cheese, Guacamole]]',
       '[Tomatillo-Red Chili Salsa (Hot), [Rice, Cheese, Sour Cream, Lettuce]]',
       '[Tomatillo Red Chili Salsa, [Rice, Black Beans, Sour Cream, Cheese, Lettuce]]',
       '[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Lettuce]]',
       '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Guacamole]]',
       '[Tomatillo Red Chili Salsa, [Cheese, Sour Cream, Lettuce]]',
       '[Tomatillo Red Chili Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]',
       '[Tomatillo Red Chili Salsa, [Black Beans, Cheese, Guacamole]]',
       '[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream]]',
       '[Fresh Tomato Salsa, Fajita Vegetables]',
       '[Fresh Tomato (Mild), [Lettuce, Guacamole, Rice, Cheese]]',
       '[Fresh Tomato Salsa, Sour Cream]',
       '[[Fresh Tomato Salsa (Mild), Tomatillo-Green Chili Salsa (Medium), Roasted Chili Corn Salsa (Medium)], [Black Beans, Rice, Fajita Veggies, Cheese, Guacamole, Lettuce]]',
       '[Tomatillo Red Chili Salsa]',
       '[Fresh Tomato Salsa, [Sour Cream, Lettuce]]',
       '[Braised Carnitas, Pinto Beans, [Sour Cream, Cheese, Cilantro-Lime Rice]]',
       '[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]',
       '[Fresh Tomato Salsa, [Sour Cream, Lettuce, Cheese, Rice]]',
       '[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice, Cheese, Sour Cream, Lettuce]]',
       '[Tomatillo Green Chili Salsa, [Black Beans, Sour Cream, Cheese, Lettuce, Guacamole]]',
       '[Tomatillo Red Chili Salsa, [Fajita Vegetables, Black Beans, Cheese, Guacamole, Lettuce]]',
       '[Tomatillo Green Chili Salsa, [Black Beans, Cheese, Guacamole]]',
       '[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]',
       '[Fresh Tomato Salsa (Mild), [Rice, Sour Cream, Cheese, Pinto Beans]]',
       '[Fresh Tomato Salsa, [Black Beans, Cheese, Guacamole]]',
       '[Roasted Chili Corn Salsa (Medium), [Black Beans, Rice, Cheese]]'],
      dtype=object)

#### 14. Find the total quantity of Veggie Salad Bowl sold.

In [33]:
df[df['item_name']=='Veggie Salad Bowl']['quantity'].sum()

np.int64(5)

#### 15. Find the total revenue generated for each item_name and list the top 5 unique items by revenue

In [41]:
df['Revenue'] = df['item_price'] * df['quantity']
df.groupby('item_name')['Revenue'].sum().sort_values(ascending=False).head(5)

item_name
Chicken Bowl           1384.22
Chicken Burrito        1240.74
Steak Burrito          1060.89
Chips and Guacamole     512.44
Steak Bowl              420.05
Name: Revenue, dtype: float64