## TASK 08 - Iris Case Study
> + Name : Anvesh Hirve
> + Batch no : 550
> + Module : EDA - Exploratory Data Analysis

In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Anvesh\OneDrive\Desktop\Innomatics Research Labs Module\EDA_550\data\data\Iris.csv")

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

#### 1. What type of data does each column in the Iris dataset contain?

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

#### 2. What are the dimensions of the Iris dataset?

In [5]:
df.shape

(150, 6)

#### 3. How many unique species of flowers are present in the dataset, and what are their names?

In [6]:
print(df['Species'].nunique())
print(df['Species'].unique())

3
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

#### 4. Check if there are any nan values in the dataset.

In [7]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

#### 5. Convert the "id" column from int to float.

In [8]:
df['Id'].dtypes

dtype('int64')

In [9]:
df['Id'] = df['Id'].astype(float)

In [10]:
df['Id'].dtypes

dtype('float64')

#### 6. What is the range of values for the ‘SepalLengthCm’ and ‘PetalWidthCm’?

In [11]:
range_values_sepallengthcm = df['SepalLengthCm'].max()-df['SepalLengthCm'].min()
range_values_pepalwidthcm = df['PetalWidthCm'].max()-df['PetalWidthCm'].min()

In [12]:
range_values_sepallengthcm

3.6000000000000005

In [13]:
range_values_pepalwidthcm

2.4

#### 7. What is the mean and median of the ‘PetalLengthCm’ column?

In [14]:
df['PetalLengthCm'].mean()

np.float64(3.758666666666666)

In [15]:
df['PetalLengthCm'].median()

4.35

#### 8. What does the df.describe().T function do, and how can it help in performing exploratory data analysis on the Iris dataset? Interpret the output.

> + `df.describe().T` helps you quickly understand the distribution, central tendency, spread, minimum/maximum values, and quartiles of the Iris measurements. It can also help you notice unusual values or possible outliers.

In [16]:
df.describe().T

               count       mean        std  min    25%    50%     75%    max
Id             150.0  75.500000  43.445368  1.0  38.25  75.50  112.75  150.0
SepalLengthCm  150.0   5.843333   0.828066  4.3   5.10   5.80    6.40    7.9
SepalWidthCm   150.0   3.054000   0.433594  2.0   2.80   3.00    3.30    4.4
PetalLengthCm  150.0   3.758667   1.764420  1.0   1.60   4.35    5.10    6.9
PetalWidthCm   150.0   1.198667   0.763161  0.1   0.30   1.30    1.80    2.5

#### 9. How would you select the first five rows of the Iris dataset using iloc

In [17]:
df.iloc[0:5]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
4  5.0            5.0           3.6            1.4           0.2  Iris-setosa

#### 10. How can you access the 'PetalLengthCm' column for rows where the index label is 'iris-setosa' using loc?

In [18]:
df.loc[df['Species']=='Iris-setosa','PetalLengthCm']

0     1.4
1     1.4
2     1.3
3     1.5
4     1.4
5     1.7
6     1.4
7     1.5
8     1.4
9     1.5
10    1.5
11    1.6
12    1.4
13    1.1
14    1.2
15    1.5
16    1.3
17    1.4
18    1.7
19    1.5
20    1.7
21    1.5
22    1.0
23    1.7
24    1.9
25    1.6
26    1.6
27    1.5
28    1.4
29    1.6
30    1.6
31    1.5
32    1.5
33    1.4
34    1.5
35    1.2
36    1.3
37    1.5
38    1.3
39    1.5
40    1.3
41    1.3
42    1.3
43    1.6
44    1.9
45    1.4
46    1.6
47    1.4
48    1.5
49    1.4
Name: PetalLengthCm, dtype: float64

#### 11. How would you filter the dataset to include only rows where 'SepalLengthCm' is greater than 5.0 and 'PetalWidthCm' is less than 1.5 using the & operator?

In [30]:
df[['SepalLengthCm','PetalWidthCm']][(df['SepalLengthCm']>5.0) & (df['PetalWidthCm']<1.5)]

     SepalLengthCm  PetalWidthCm
0              5.1           0.2
5              5.4           0.4
10             5.4           0.2
14             5.8           0.2
15             5.7           0.4
16             5.4           0.4
17             5.1           0.3
18             5.7           0.3
19             5.1           0.3
20             5.4           0.2
21             5.1           0.4
23             5.1           0.5
27             5.2           0.2
28             5.2           0.2
31             5.4           0.4
32             5.2           0.1
33             5.5           0.2
36             5.5           0.2
39             5.1           0.2
44             5.1           0.4
46             5.1           0.2
48             5.3           0.2
50             7.0           1.4
53             5.5           1.3
55             5.7           1.3
58             6.6           1.3
59             5.2           1.4
62             6.0           1.0
63             6.1           1.4
64             5.6           1.3
65             6.7           1.4
67             5.8           1.0
69             5.6           1.1
71             6.1           1.3
73             6.1           1.2
74             6.4           1.3
75             6.6           1.4
76             6.8           1.4
79             5.7           1.0
80             5.5           1.1
81             5.5           1.0
82             5.8           1.2
87             6.3           1.3
88             5.6           1.3
89             5.5           1.3
90             5.5           1.2
91             6.1           1.4
92             5.8           1.2
94             5.6           1.3
95             5.7           1.2
96             5.7           1.3
97             6.2           1.3
98             5.1           1.1
99             5.7           1.3
134            6.1           1.4

#### 12. Using loc and & to Select Rows Labeled 'Versicolor' where 'SepalLengthCm' is Between 5.5 and 6.5

In [34]:
df[['Species','SepalLengthCm']].loc[(df['Species']=='Iris-versicolor') & (df['SepalLengthCm']>5.5) & (df['SepalLengthCm']<6.5)]

            Species  SepalLengthCm
51  Iris-versicolor            6.4
55  Iris-versicolor            5.7
56  Iris-versicolor            6.3
61  Iris-versicolor            5.9
62  Iris-versicolor            6.0
63  Iris-versicolor            6.1
64  Iris-versicolor            5.6
66  Iris-versicolor            5.6
67  Iris-versicolor            5.8
68  Iris-versicolor            6.2
69  Iris-versicolor            5.6
70  Iris-versicolor            5.9
71  Iris-versicolor            6.1
72  Iris-versicolor            6.3
73  Iris-versicolor            6.1
74  Iris-versicolor            6.4
78  Iris-versicolor            6.0
79  Iris-versicolor            5.7
82  Iris-versicolor            5.8
83  Iris-versicolor            6.0
85  Iris-versicolor            6.0
87  Iris-versicolor            6.3
88  Iris-versicolor            5.6
91  Iris-versicolor            6.1
92  Iris-versicolor            5.8
94  Iris-versicolor            5.6
95  Iris-versicolor            5.7
96  Iris-versicolor            5.7
97  Iris-versicolor            6.2
99  Iris-versicolor            5.7

#### 13. Using loc and | to Filter Rows Labeled 'Virginica' or 'Setosa' with 'Petal'WidthCm' Greater Than 2.0

In [33]:
df[['Species','PetalWidthCm']].loc[((df['Species']=='Iris-virginica') | (df['Species']=='Iris-setosa')) & (df['PetalWidthCm']>2.0)]

            Species  PetalWidthCm
100  Iris-virginica           2.5
102  Iris-virginica           2.1
104  Iris-virginica           2.2
105  Iris-virginica           2.1
109  Iris-virginica           2.5
112  Iris-virginica           2.1
114  Iris-virginica           2.4
115  Iris-virginica           2.3
117  Iris-virginica           2.2
118  Iris-virginica           2.3
120  Iris-virginica           2.3
124  Iris-virginica           2.1
128  Iris-virginica           2.1
132  Iris-virginica           2.2
135  Iris-virginica           2.3
136  Iris-virginica           2.4
139  Iris-virginica           2.1
140  Iris-virginica           2.4
141  Iris-virginica           2.3
143  Iris-virginica           2.3
144  Iris-virginica           2.5
145  Iris-virginica           2.3
148  Iris-virginica           2.3